name: Python Application CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install g++ -y
          pip install telebot pymongo aiohttp
          pip install pymongo python-telegram-bot pyTelegramBotAPI certifi

      - name: Compile C++ Code
        run: g++ -std=c++14 soul.cpp -o soul -pthread

     # - name: Run C++ Executable
       # run: ./soul  # Ensure the compiled C++ program is executed

      - name: Run Python Application
        run: python soul.py  # Python script execution

