name: Build and Run C++ & Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Make sure it's an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install g++ -y
        sudo apt install python3-pip -y
        pip3 install telebot pymongo aiohttp

    - name: Compile C++ code
      run: g++ -std=c++14 soul.cpp -o soul -pthread

    - name: Run Python script
      run: python3 soul.py
